name: Docker Deploy

on:
  push:
    tags:
      - '*'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew distTar
      - run: echo ::set-output name=version::$(echo "${{ github.ref }}" | sed -e "s/^refs\/tags\///")
        id: tag_version
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag_version.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
